# Generated by Django 5.2.3 on 2025-07-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistribuidorPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del distribuidor o alias visible', max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, help_text='Dirección física (opcional si hay geolocalización)', max_length=255)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('url_mapa', models.URLField(blank=True, help_text='URL de Google Maps si está disponible')),
                ('tamano_cilindro', models.IntegerField(choices=[(5, '5 kilos'), (15, '15 kilos'), (45, '45 kilos')])),
                ('precio', models.PositiveIntegerField(help_text='Precio en pesos chilenos')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Precio de distribuidor',
                'verbose_name_plural': 'Precios de distribuidores',
                'ordering': ['region', 'comuna', 'nombre', 'tamano_cilindro'],
            },
        ),
    ]
