# Generated by Django 5.2.3 on 2025-07-02 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribuidorprecio',
            options={},
        ),
        migrations.AddField(
            model_name='distribuidorprecio',
            name='distribuidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='distribuidorprecio',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='distribuidorprecio',
            name='nombre',
            field=models.CharField(help_text='Nombre o alias visible del local', max_length=100),
        ),
        migrations.AlterField(
            model_name='distribuidorprecio',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='distribuidorprecio',
            name='url_mapa',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='DistribuidorUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fantasia', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
