# Generated by Django 5.2.3 on 2025-07-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_distribuidorprecio_distribuidor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribuidorprecio',
            name='precio',
        ),
        migrations.AddField(
            model_name='distribuidorprecio',
            name='precio_despacho',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distribuidorprecio',
            name='precio_retiro',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
